CREATE TABLE IF NOT EXISTS `Score` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user` VARCHAR(100) NOT NULL,
    `score` INT(255) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`user`)
)